// Code generated by `make package-data`. DO NOT EDIT.

package genai_prices

const (
	// UsageInputTokens identifies the input_tokens usage value.
	UsageInputTokens UsageKey = "input_tokens"
	// UsageOutputTokens identifies the output_tokens usage value.
	UsageOutputTokens UsageKey = "output_tokens"
	// UsageCacheReadTokens identifies the cache_read_tokens usage value.
	UsageCacheReadTokens UsageKey = "cache_read_tokens"
	// UsageCacheWriteTokens identifies the cache_write_tokens usage value.
	UsageCacheWriteTokens UsageKey = "cache_write_tokens"
	// UsageCacheWrite5MTokens identifies the cache_write_5m_tokens usage value.
	UsageCacheWrite5MTokens UsageKey = "cache_write_5m_tokens"
	// UsageCacheWrite1HTokens identifies the cache_write_1h_tokens usage value.
	UsageCacheWrite1HTokens UsageKey = "cache_write_1h_tokens"
	// UsageInputTextTokens identifies the input_text_tokens usage value.
	UsageInputTextTokens UsageKey = "input_text_tokens"
	// UsageOutputTextTokens identifies the output_text_tokens usage value.
	UsageOutputTextTokens UsageKey = "output_text_tokens"
	// UsageCacheTextReadTokens identifies the cache_text_read_tokens usage value.
	UsageCacheTextReadTokens UsageKey = "cache_text_read_tokens"
	// UsageCacheTextWriteTokens identifies the cache_text_write_tokens usage value.
	UsageCacheTextWriteTokens UsageKey = "cache_text_write_tokens"
	// UsageCacheTextWrite5MTokens identifies the cache_text_write_5m_tokens usage value.
	UsageCacheTextWrite5MTokens UsageKey = "cache_text_write_5m_tokens"
	// UsageCacheTextWrite1HTokens identifies the cache_text_write_1h_tokens usage value.
	UsageCacheTextWrite1HTokens UsageKey = "cache_text_write_1h_tokens"
	// UsageInputAudioTokens identifies the input_audio_tokens usage value.
	UsageInputAudioTokens UsageKey = "input_audio_tokens"
	// UsageOutputAudioTokens identifies the output_audio_tokens usage value.
	UsageOutputAudioTokens UsageKey = "output_audio_tokens"
	// UsageCacheAudioReadTokens identifies the cache_audio_read_tokens usage value.
	UsageCacheAudioReadTokens UsageKey = "cache_audio_read_tokens"
	// UsageCacheAudioWriteTokens identifies the cache_audio_write_tokens usage value.
	UsageCacheAudioWriteTokens UsageKey = "cache_audio_write_tokens"
	// UsageCacheAudioWrite5MTokens identifies the cache_audio_write_5m_tokens usage value.
	UsageCacheAudioWrite5MTokens UsageKey = "cache_audio_write_5m_tokens"
	// UsageCacheAudioWrite1HTokens identifies the cache_audio_write_1h_tokens usage value.
	UsageCacheAudioWrite1HTokens UsageKey = "cache_audio_write_1h_tokens"
	// UsageInputImageTokens identifies the input_image_tokens usage value.
	UsageInputImageTokens UsageKey = "input_image_tokens"
	// UsageOutputImageTokens identifies the output_image_tokens usage value.
	UsageOutputImageTokens UsageKey = "output_image_tokens"
	// UsageCacheImageReadTokens identifies the cache_image_read_tokens usage value.
	UsageCacheImageReadTokens UsageKey = "cache_image_read_tokens"
	// UsageCacheImageWriteTokens identifies the cache_image_write_tokens usage value.
	UsageCacheImageWriteTokens UsageKey = "cache_image_write_tokens"
	// UsageCacheImageWrite5MTokens identifies the cache_image_write_5m_tokens usage value.
	UsageCacheImageWrite5MTokens UsageKey = "cache_image_write_5m_tokens"
	// UsageCacheImageWrite1HTokens identifies the cache_image_write_1h_tokens usage value.
	UsageCacheImageWrite1HTokens UsageKey = "cache_image_write_1h_tokens"
	// UsageInputVideoTokens identifies the input_video_tokens usage value.
	UsageInputVideoTokens UsageKey = "input_video_tokens"
	// UsageOutputVideoTokens identifies the output_video_tokens usage value.
	UsageOutputVideoTokens UsageKey = "output_video_tokens"
	// UsageCacheVideoReadTokens identifies the cache_video_read_tokens usage value.
	UsageCacheVideoReadTokens UsageKey = "cache_video_read_tokens"
	// UsageCacheVideoWriteTokens identifies the cache_video_write_tokens usage value.
	UsageCacheVideoWriteTokens UsageKey = "cache_video_write_tokens"
	// UsageCacheVideoWrite5MTokens identifies the cache_video_write_5m_tokens usage value.
	UsageCacheVideoWrite5MTokens UsageKey = "cache_video_write_5m_tokens"
	// UsageCacheVideoWrite1HTokens identifies the cache_video_write_1h_tokens usage value.
	UsageCacheVideoWrite1HTokens UsageKey = "cache_video_write_1h_tokens"
	// UsageInputToolTokens identifies the input_tool_tokens usage value.
	UsageInputToolTokens UsageKey = "input_tool_tokens"
	// UsageInputTextToolTokens identifies the input_text_tool_tokens usage value.
	UsageInputTextToolTokens UsageKey = "input_text_tool_tokens"
	// UsageInputAudioToolTokens identifies the input_audio_tool_tokens usage value.
	UsageInputAudioToolTokens UsageKey = "input_audio_tool_tokens"
	// UsageInputImageToolTokens identifies the input_image_tool_tokens usage value.
	UsageInputImageToolTokens UsageKey = "input_image_tool_tokens"
	// UsageInputVideoToolTokens identifies the input_video_tool_tokens usage value.
	UsageInputVideoToolTokens UsageKey = "input_video_tool_tokens"
	// UsageOutputReasoningTokens identifies the output_reasoning_tokens usage value.
	UsageOutputReasoningTokens UsageKey = "output_reasoning_tokens"
	// UsageOutputTextReasoningTokens identifies the output_text_reasoning_tokens usage value.
	UsageOutputTextReasoningTokens UsageKey = "output_text_reasoning_tokens"
	// UsageOutputAudioReasoningTokens identifies the output_audio_reasoning_tokens usage value.
	UsageOutputAudioReasoningTokens UsageKey = "output_audio_reasoning_tokens"
	// UsageOutputImageReasoningTokens identifies the output_image_reasoning_tokens usage value.
	UsageOutputImageReasoningTokens UsageKey = "output_image_reasoning_tokens"
	// UsageOutputVideoReasoningTokens identifies the output_video_reasoning_tokens usage value.
	UsageOutputVideoReasoningTokens UsageKey = "output_video_reasoning_tokens"
	// UsageOutputCitationTokens identifies the output_citation_tokens usage value.
	UsageOutputCitationTokens UsageKey = "output_citation_tokens"
	// UsageOutputTextCitationTokens identifies the output_text_citation_tokens usage value.
	UsageOutputTextCitationTokens UsageKey = "output_text_citation_tokens"
	// UsageOutputAudioCitationTokens identifies the output_audio_citation_tokens usage value.
	UsageOutputAudioCitationTokens UsageKey = "output_audio_citation_tokens"
	// UsageOutputImageCitationTokens identifies the output_image_citation_tokens usage value.
	UsageOutputImageCitationTokens UsageKey = "output_image_citation_tokens"
	// UsageOutputVideoCitationTokens identifies the output_video_citation_tokens usage value.
	UsageOutputVideoCitationTokens UsageKey = "output_video_citation_tokens"
	// UsageInputCharacters identifies the input_characters usage value.
	UsageInputCharacters UsageKey = "input_characters"
	// UsageInputTextMessages identifies the input_text_messages usage value.
	UsageInputTextMessages UsageKey = "input_text_messages"
	// UsageAudioSeconds identifies the audio_seconds usage value.
	UsageAudioSeconds UsageKey = "audio_seconds"
	// UsageInputAudioSeconds identifies the input_audio_seconds usage value.
	UsageInputAudioSeconds UsageKey = "input_audio_seconds"
	// UsageOutputAudioSeconds identifies the output_audio_seconds usage value.
	UsageOutputAudioSeconds UsageKey = "output_audio_seconds"
	// UsageInputPixels identifies the input_pixels usage value.
	UsageInputPixels UsageKey = "input_pixels"
	// UsageInputDocumentPages identifies the input_document_pages usage value.
	UsageInputDocumentPages UsageKey = "input_document_pages"
	// UsageInputAnnotatedDocumentPages identifies the input_annotated_document_pages usage value.
	UsageInputAnnotatedDocumentPages UsageKey = "input_annotated_document_pages"
	// UsageRerankSearches identifies the rerank_searches usage value.
	UsageRerankSearches UsageKey = "rerank_searches"
	// UsageWebSearches identifies the web_searches usage value.
	UsageWebSearches UsageKey = "web_searches"
	// UsageSocialSearches identifies the social_searches usage value.
	UsageSocialSearches UsageKey = "social_searches"
	// UsageStorageSearches identifies the storage_searches usage value.
	UsageStorageSearches UsageKey = "storage_searches"
	// UsageCodeExecutions identifies the code_executions usage value.
	UsageCodeExecutions UsageKey = "code_executions"
	// UsageRequests identifies the requests usage value.
	UsageRequests UsageKey = "requests"
)

var bundledUnitOrder = []UsageKey{
	UsageInputTokens,
	UsageOutputTokens,
	UsageCacheReadTokens,
	UsageCacheWriteTokens,
	UsageCacheWrite5MTokens,
	UsageCacheWrite1HTokens,
	UsageInputTextTokens,
	UsageOutputTextTokens,
	UsageCacheTextReadTokens,
	UsageCacheTextWriteTokens,
	UsageCacheTextWrite5MTokens,
	UsageCacheTextWrite1HTokens,
	UsageInputAudioTokens,
	UsageOutputAudioTokens,
	UsageCacheAudioReadTokens,
	UsageCacheAudioWriteTokens,
	UsageCacheAudioWrite5MTokens,
	UsageCacheAudioWrite1HTokens,
	UsageInputImageTokens,
	UsageOutputImageTokens,
	UsageCacheImageReadTokens,
	UsageCacheImageWriteTokens,
	UsageCacheImageWrite5MTokens,
	UsageCacheImageWrite1HTokens,
	UsageInputVideoTokens,
	UsageOutputVideoTokens,
	UsageCacheVideoReadTokens,
	UsageCacheVideoWriteTokens,
	UsageCacheVideoWrite5MTokens,
	UsageCacheVideoWrite1HTokens,
	UsageInputToolTokens,
	UsageInputTextToolTokens,
	UsageInputAudioToolTokens,
	UsageInputImageToolTokens,
	UsageInputVideoToolTokens,
	UsageOutputReasoningTokens,
	UsageOutputTextReasoningTokens,
	UsageOutputAudioReasoningTokens,
	UsageOutputImageReasoningTokens,
	UsageOutputVideoReasoningTokens,
	UsageOutputCitationTokens,
	UsageOutputTextCitationTokens,
	UsageOutputAudioCitationTokens,
	UsageOutputImageCitationTokens,
	UsageOutputVideoCitationTokens,
	UsageInputCharacters,
	UsageInputTextMessages,
	UsageAudioSeconds,
	UsageInputAudioSeconds,
	UsageOutputAudioSeconds,
	UsageInputPixels,
	UsageInputDocumentPages,
	UsageInputAnnotatedDocumentPages,
	UsageRerankSearches,
	UsageWebSearches,
	UsageSocialSearches,
	UsageStorageSearches,
	UsageCodeExecutions,
	UsageRequests,
}

var bundledUnits = map[UsageKey]unitDef{
	UsageInputTokens:                 {priceKey: "input_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens"}},
	UsageOutputTokens:                {priceKey: "output_mtok", per: 1000000, dimensions: map[string]string{"direction": "output", "family": "tokens"}},
	UsageCacheReadTokens:             {priceKey: "cache_read_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "token_type": "cache_read"}},
	UsageCacheWriteTokens:            {priceKey: "cache_write_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "token_type": "cache_write"}},
	UsageCacheWrite5MTokens:          {priceKey: "cache_write_5m_mtok", per: 1000000, dimensions: map[string]string{"cache_ttl": "5m", "direction": "input", "family": "tokens", "token_type": "cache_write"}},
	UsageCacheWrite1HTokens:          {priceKey: "cache_write_1h_mtok", per: 1000000, dimensions: map[string]string{"cache_ttl": "1h", "direction": "input", "family": "tokens", "token_type": "cache_write"}},
	UsageInputTextTokens:             {priceKey: "input_text_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "modality": "text"}},
	UsageOutputTextTokens:            {priceKey: "output_text_mtok", per: 1000000, dimensions: map[string]string{"direction": "output", "family": "tokens", "modality": "text"}},
	UsageCacheTextReadTokens:         {priceKey: "cache_text_read_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "modality": "text", "token_type": "cache_read"}},
	UsageCacheTextWriteTokens:        {priceKey: "cache_text_write_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "modality": "text", "token_type": "cache_write"}},
	UsageCacheTextWrite5MTokens:      {priceKey: "cache_text_write_5m_mtok", per: 1000000, dimensions: map[string]string{"cache_ttl": "5m", "direction": "input", "family": "tokens", "modality": "text", "token_type": "cache_write"}},
	UsageCacheTextWrite1HTokens:      {priceKey: "cache_text_write_1h_mtok", per: 1000000, dimensions: map[string]string{"cache_ttl": "1h", "direction": "input", "family": "tokens", "modality": "text", "token_type": "cache_write"}},
	UsageInputAudioTokens:            {priceKey: "input_audio_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "modality": "audio"}},
	UsageOutputAudioTokens:           {priceKey: "output_audio_mtok", per: 1000000, dimensions: map[string]string{"direction": "output", "family": "tokens", "modality": "audio"}},
	UsageCacheAudioReadTokens:        {priceKey: "cache_audio_read_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "modality": "audio", "token_type": "cache_read"}},
	UsageCacheAudioWriteTokens:       {priceKey: "cache_audio_write_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "modality": "audio", "token_type": "cache_write"}},
	UsageCacheAudioWrite5MTokens:     {priceKey: "cache_audio_write_5m_mtok", per: 1000000, dimensions: map[string]string{"cache_ttl": "5m", "direction": "input", "family": "tokens", "modality": "audio", "token_type": "cache_write"}},
	UsageCacheAudioWrite1HTokens:     {priceKey: "cache_audio_write_1h_mtok", per: 1000000, dimensions: map[string]string{"cache_ttl": "1h", "direction": "input", "family": "tokens", "modality": "audio", "token_type": "cache_write"}},
	UsageInputImageTokens:            {priceKey: "input_image_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "modality": "image"}},
	UsageOutputImageTokens:           {priceKey: "output_image_mtok", per: 1000000, dimensions: map[string]string{"direction": "output", "family": "tokens", "modality": "image"}},
	UsageCacheImageReadTokens:        {priceKey: "cache_image_read_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "modality": "image", "token_type": "cache_read"}},
	UsageCacheImageWriteTokens:       {priceKey: "cache_image_write_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "modality": "image", "token_type": "cache_write"}},
	UsageCacheImageWrite5MTokens:     {priceKey: "cache_image_write_5m_mtok", per: 1000000, dimensions: map[string]string{"cache_ttl": "5m", "direction": "input", "family": "tokens", "modality": "image", "token_type": "cache_write"}},
	UsageCacheImageWrite1HTokens:     {priceKey: "cache_image_write_1h_mtok", per: 1000000, dimensions: map[string]string{"cache_ttl": "1h", "direction": "input", "family": "tokens", "modality": "image", "token_type": "cache_write"}},
	UsageInputVideoTokens:            {priceKey: "input_video_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "modality": "video"}},
	UsageOutputVideoTokens:           {priceKey: "output_video_mtok", per: 1000000, dimensions: map[string]string{"direction": "output", "family": "tokens", "modality": "video"}},
	UsageCacheVideoReadTokens:        {priceKey: "cache_video_read_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "modality": "video", "token_type": "cache_read"}},
	UsageCacheVideoWriteTokens:       {priceKey: "cache_video_write_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "modality": "video", "token_type": "cache_write"}},
	UsageCacheVideoWrite5MTokens:     {priceKey: "cache_video_write_5m_mtok", per: 1000000, dimensions: map[string]string{"cache_ttl": "5m", "direction": "input", "family": "tokens", "modality": "video", "token_type": "cache_write"}},
	UsageCacheVideoWrite1HTokens:     {priceKey: "cache_video_write_1h_mtok", per: 1000000, dimensions: map[string]string{"cache_ttl": "1h", "direction": "input", "family": "tokens", "modality": "video", "token_type": "cache_write"}},
	UsageInputToolTokens:             {priceKey: "input_tool_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "token_type": "tool"}},
	UsageInputTextToolTokens:         {priceKey: "input_text_tool_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "modality": "text", "token_type": "tool"}},
	UsageInputAudioToolTokens:        {priceKey: "input_audio_tool_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "modality": "audio", "token_type": "tool"}},
	UsageInputImageToolTokens:        {priceKey: "input_image_tool_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "modality": "image", "token_type": "tool"}},
	UsageInputVideoToolTokens:        {priceKey: "input_video_tool_mtok", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "tokens", "modality": "video", "token_type": "tool"}},
	UsageOutputReasoningTokens:       {priceKey: "output_reasoning_mtok", per: 1000000, dimensions: map[string]string{"direction": "output", "family": "tokens", "token_type": "reasoning"}},
	UsageOutputTextReasoningTokens:   {priceKey: "output_text_reasoning_mtok", per: 1000000, dimensions: map[string]string{"direction": "output", "family": "tokens", "modality": "text", "token_type": "reasoning"}},
	UsageOutputAudioReasoningTokens:  {priceKey: "output_audio_reasoning_mtok", per: 1000000, dimensions: map[string]string{"direction": "output", "family": "tokens", "modality": "audio", "token_type": "reasoning"}},
	UsageOutputImageReasoningTokens:  {priceKey: "output_image_reasoning_mtok", per: 1000000, dimensions: map[string]string{"direction": "output", "family": "tokens", "modality": "image", "token_type": "reasoning"}},
	UsageOutputVideoReasoningTokens:  {priceKey: "output_video_reasoning_mtok", per: 1000000, dimensions: map[string]string{"direction": "output", "family": "tokens", "modality": "video", "token_type": "reasoning"}},
	UsageOutputCitationTokens:        {priceKey: "output_citation_mtok", per: 1000000, dimensions: map[string]string{"direction": "output", "family": "tokens", "token_type": "citation"}},
	UsageOutputTextCitationTokens:    {priceKey: "output_text_citation_mtok", per: 1000000, dimensions: map[string]string{"direction": "output", "family": "tokens", "modality": "text", "token_type": "citation"}},
	UsageOutputAudioCitationTokens:   {priceKey: "output_audio_citation_mtok", per: 1000000, dimensions: map[string]string{"direction": "output", "family": "tokens", "modality": "audio", "token_type": "citation"}},
	UsageOutputImageCitationTokens:   {priceKey: "output_image_citation_mtok", per: 1000000, dimensions: map[string]string{"direction": "output", "family": "tokens", "modality": "image", "token_type": "citation"}},
	UsageOutputVideoCitationTokens:   {priceKey: "output_video_citation_mtok", per: 1000000, dimensions: map[string]string{"direction": "output", "family": "tokens", "modality": "video", "token_type": "citation"}},
	UsageInputCharacters:             {priceKey: "input_mchars", per: 1000000, dimensions: map[string]string{"direction": "input", "family": "characters"}},
	UsageInputTextMessages:           {priceKey: "input_text_messages_kcount", per: 1000, dimensions: map[string]string{"direction": "input", "family": "messages", "modality": "text"}},
	UsageAudioSeconds:                {priceKey: "audio_hours", per: 3600, dimensions: map[string]string{"family": "durations", "modality": "audio"}},
	UsageInputAudioSeconds:           {priceKey: "input_audio_hours", per: 3600, dimensions: map[string]string{"direction": "input", "family": "durations", "modality": "audio"}},
	UsageOutputAudioSeconds:          {priceKey: "output_audio_hours", per: 3600, dimensions: map[string]string{"direction": "output", "family": "durations", "modality": "audio"}},
	UsageInputPixels:                 {priceKey: "input_gpixels", per: 1000000000, dimensions: map[string]string{"direction": "input", "family": "pixels"}},
	UsageInputDocumentPages:          {priceKey: "input_document_kpages", per: 1000, dimensions: map[string]string{"direction": "input", "family": "document_pages"}},
	UsageInputAnnotatedDocumentPages: {priceKey: "input_annotated_document_kpages", per: 1000, dimensions: map[string]string{"direction": "input", "family": "document_pages", "page_type": "annotated"}},
	UsageRerankSearches:              {priceKey: "rerank_searches_kcount", per: 1000, dimensions: map[string]string{"family": "rerank"}},
	UsageWebSearches:                 {priceKey: "web_searches_kcount", per: 1000, dimensions: map[string]string{"family": "tool_calls", "tool_type": "web_search"}},
	UsageSocialSearches:              {priceKey: "social_searches_kcount", per: 1000, dimensions: map[string]string{"family": "tool_calls", "tool_type": "social_search"}},
	UsageStorageSearches:             {priceKey: "storage_searches_kcount", per: 1000, dimensions: map[string]string{"family": "tool_calls", "tool_type": "storage_search"}},
	UsageCodeExecutions:              {priceKey: "code_executions_kcount", per: 1000, dimensions: map[string]string{"family": "tool_calls", "tool_type": "code_execution"}},
	UsageRequests:                    {priceKey: "requests_kcount", per: 1000, dimensions: map[string]string{"family": "requests"}},
}
