// DO NOT EDIT THIS FILE DIRECTLY, INSTEAD RUN `make package-data`
import type { RawFamiliesDict } from './types'
export const unitFamiliesData: RawFamiliesDict = {
  requests: {
    description: 'Request counts. Explicit special case: one per Usage object passed to calc_price; not caller-supplied Usage.',
    per: 1000,
    units: {
      requests: {
        dimensions: {},
        price_key: 'requests_kcount',
      },
    },
  },
  tokens: {
    description: 'Token counts',
    per: 1000000,
    units: {
      cache_audio_read_tokens: {
        dimensions: {
          cache: 'read',
          direction: 'input',
          modality: 'audio',
        },
        price_key: 'cache_audio_read_mtok',
      },
      cache_read_tokens: {
        dimensions: {
          cache: 'read',
          direction: 'input',
        },
        price_key: 'cache_read_mtok',
      },
      cache_write_tokens: {
        dimensions: {
          cache: 'write',
          direction: 'input',
        },
        price_key: 'cache_write_mtok',
      },
      input_audio_tokens: {
        dimensions: {
          direction: 'input',
          modality: 'audio',
        },
        price_key: 'input_audio_mtok',
      },
      input_tokens: {
        dimensions: {
          direction: 'input',
        },
        price_key: 'input_mtok',
      },
      output_audio_tokens: {
        dimensions: {
          direction: 'output',
          modality: 'audio',
        },
        price_key: 'output_audio_mtok',
      },
      output_tokens: {
        dimensions: {
          direction: 'output',
        },
        price_key: 'output_mtok',
      },
    },
  },
}
