// DO NOT EDIT THIS FILE DIRECTLY, INSTEAD RUN `make package-data`
import type { RawUnitsDict } from './types'
export const unitData: RawUnitsDict = {
  cache_audio_read_tokens: {
    dimensions: {
      cache: 'read',
      direction: 'input',
      family: 'tokens',
      modality: 'audio',
    },
    per: 1000000,
    price_key: 'cache_audio_read_mtok',
  },
  cache_audio_write_tokens: {
    dimensions: {
      cache: 'write',
      direction: 'input',
      family: 'tokens',
      modality: 'audio',
    },
    per: 1000000,
    price_key: 'cache_audio_write_mtok',
  },
  cache_image_read_tokens: {
    dimensions: {
      cache: 'read',
      direction: 'input',
      family: 'tokens',
      modality: 'image',
    },
    per: 1000000,
    price_key: 'cache_image_read_mtok',
  },
  cache_image_write_tokens: {
    dimensions: {
      cache: 'write',
      direction: 'input',
      family: 'tokens',
      modality: 'image',
    },
    per: 1000000,
    price_key: 'cache_image_write_mtok',
  },
  cache_read_tokens: {
    dimensions: {
      cache: 'read',
      direction: 'input',
      family: 'tokens',
    },
    per: 1000000,
    price_key: 'cache_read_mtok',
  },
  cache_text_read_tokens: {
    dimensions: {
      cache: 'read',
      direction: 'input',
      family: 'tokens',
      modality: 'text',
    },
    per: 1000000,
    price_key: 'cache_text_read_mtok',
  },
  cache_text_write_tokens: {
    dimensions: {
      cache: 'write',
      direction: 'input',
      family: 'tokens',
      modality: 'text',
    },
    per: 1000000,
    price_key: 'cache_text_write_mtok',
  },
  cache_video_read_tokens: {
    dimensions: {
      cache: 'read',
      direction: 'input',
      family: 'tokens',
      modality: 'video',
    },
    per: 1000000,
    price_key: 'cache_video_read_mtok',
  },
  cache_video_write_tokens: {
    dimensions: {
      cache: 'write',
      direction: 'input',
      family: 'tokens',
      modality: 'video',
    },
    per: 1000000,
    price_key: 'cache_video_write_mtok',
  },
  cache_write_tokens: {
    dimensions: {
      cache: 'write',
      direction: 'input',
      family: 'tokens',
    },
    per: 1000000,
    price_key: 'cache_write_mtok',
  },
  input_audio_tokens: {
    dimensions: {
      direction: 'input',
      family: 'tokens',
      modality: 'audio',
    },
    per: 1000000,
    price_key: 'input_audio_mtok',
  },
  input_image_tokens: {
    dimensions: {
      direction: 'input',
      family: 'tokens',
      modality: 'image',
    },
    per: 1000000,
    price_key: 'input_image_mtok',
  },
  input_text_tokens: {
    dimensions: {
      direction: 'input',
      family: 'tokens',
      modality: 'text',
    },
    per: 1000000,
    price_key: 'input_text_mtok',
  },
  input_tokens: {
    dimensions: {
      direction: 'input',
      family: 'tokens',
    },
    per: 1000000,
    price_key: 'input_mtok',
  },
  input_video_tokens: {
    dimensions: {
      direction: 'input',
      family: 'tokens',
      modality: 'video',
    },
    per: 1000000,
    price_key: 'input_video_mtok',
  },
  output_audio_tokens: {
    dimensions: {
      direction: 'output',
      family: 'tokens',
      modality: 'audio',
    },
    per: 1000000,
    price_key: 'output_audio_mtok',
  },
  output_image_tokens: {
    dimensions: {
      direction: 'output',
      family: 'tokens',
      modality: 'image',
    },
    per: 1000000,
    price_key: 'output_image_mtok',
  },
  output_text_tokens: {
    dimensions: {
      direction: 'output',
      family: 'tokens',
      modality: 'text',
    },
    per: 1000000,
    price_key: 'output_text_mtok',
  },
  output_tokens: {
    dimensions: {
      direction: 'output',
      family: 'tokens',
    },
    per: 1000000,
    price_key: 'output_mtok',
  },
  output_video_tokens: {
    dimensions: {
      direction: 'output',
      family: 'tokens',
      modality: 'video',
    },
    per: 1000000,
    price_key: 'output_video_mtok',
  },
  requests: {
    dimensions: {
      family: 'requests',
    },
    per: 1000,
    price_key: 'requests_kcount',
  },
}
