"""Tests for `prices.source_quicksilverpro` against a recorded `pricing.json`."""

from __future__ import annotations

from decimal import Decimal
from pathlib import Path
from types import SimpleNamespace

import httpx2
import pytest
from inline_snapshot import snapshot

from prices import source_quicksilverpro
from prices.prices_types import ClauseEquals, ModelPrice, UsageExtractor
from prices.source_quicksilverpro import CATALOG_URL, get_model_infos

from .fixtures import load_entries


def quicksilverpro_models() -> list[dict[str, object]]:
    return load_entries('quicksilverpro_pricing.json', 'models')


def test_quicksilverpro_catalog_rates_are_already_per_mtok():
    infos = list(get_model_infos(quicksilverpro_models()))

    assert {
        info.id: (
            info.prices.input_mtok,
            info.prices.cache_read_mtok,
            info.prices.cache_write_mtok,
            info.prices.output_mtok,
            info.context_window,
        )
        for info in infos
        if isinstance(info.prices, ModelPrice)
    } == snapshot(
        {
            'gpt-5.6-sol': (Decimal('4'), Decimal('0.4'), Decimal('5'), Decimal('24'), 1048576),
            'deepseek-v4-flash': (Decimal('0.112'), Decimal('0.0144'), None, Decimal('0.224'), 1048576),
            'gemini-3-pro-image': (Decimal('1.7'), None, None, Decimal('10.2'), 1048576),
            'gemini-3-flash-preview': (Decimal('0.425'), None, None, Decimal('2.55'), 1048576),
            'muse-spark-1.2': (Decimal('1'), Decimal('0.12'), None, Decimal('3.4'), 1048576),
        }
    )


def test_quicksilverpro_image_output_rate_is_recorded():
    infos = {info.id: info for info in get_model_infos(quicksilverpro_models())}
    prices = infos['gemini-3-pro-image'].prices
    assert isinstance(prices, ModelPrice)

    assert prices.model_dump(exclude_none=True)['output_image_mtok'] == Decimal('102')


def test_quicksilverpro_skips_per_image_models():
    """FLUX is billed per image, which has no unit in the registry."""
    ids = [info.id for info in get_model_infos(quicksilverpro_models())]

    assert 'flux.2-pro' not in ids


def test_quicksilverpro_flags_deprecated_models():
    infos = {info.id: info for info in get_model_infos(quicksilverpro_models())}

    assert infos['gemini-3-flash-preview'].deprecated is True
    assert infos['gpt-5.6-sol'].deprecated is None
    assert infos['gpt-5.6-sol'].match == ClauseEquals(equals='gpt-5.6-sol')
    assert infos['gpt-5.6-sol'].name == 'GPT-5.6 Sol'


def test_quicksilverpro_main_writes_and_collapses_generated_provider(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, capsys: pytest.CaptureFixture[str]
):
    class FakeResponse:
        def raise_for_status(self) -> None:
            pass

        def json(self) -> dict[str, list[dict[str, object]]]:
            return {'models': quicksilverpro_models()}

    class FakeProviderYaml:
        instances: list[FakeProviderYaml] = []

        def __init__(self, path: Path) -> None:
            self.path = path
            self.provider = SimpleNamespace(
                extractors=[
                    UsageExtractor(api_flavor='chat', root='usage', mappings=[]),
                    UsageExtractor(api_flavor='responses', root='usage', mappings=[]),
                    UsageExtractor(api_flavor='realtime', root='usage', mappings=[]),
                ],
            )
            self.saved = False
            self.instances.append(self)

        def save(self) -> None:
            self.saved = True

    source_file = tmp_path / 'src' / 'prices' / 'source_quicksilverpro.py'
    source_file.parent.mkdir(parents=True)
    providers_dir = tmp_path / 'providers'
    providers_dir.mkdir()

    def fake_path(_: str) -> Path:
        return source_file

    def fake_get(url: str, *, timeout: float) -> FakeResponse:
        assert url == CATALOG_URL
        assert timeout == 30.0
        return FakeResponse()

    monkeypatch.setattr(source_quicksilverpro, 'Path', fake_path)
    monkeypatch.setattr(source_quicksilverpro, 'ProviderYaml', FakeProviderYaml)
    monkeypatch.setattr(httpx2, 'get', fake_get)
    collapse_results = iter([True, False])

    def fake_collapse(_: FakeProviderYaml) -> bool:
        return next(collapse_results)

    monkeypatch.setattr(source_quicksilverpro, 'collapse_provider', fake_collapse)

    source_quicksilverpro.main()
    source_quicksilverpro.main()

    output_path = providers_dir / 'quicksilverpro.yml'
    assert output_path.is_file()
    output_yaml = output_path.read_text()
    assert 'auto-generated by source_quicksilverpro.py' in output_yaml
    assert '- id: gpt-5.6-sol' in output_yaml
    assert 'flux.2-pro' not in output_yaml
    # only the OpenAI-compatible flavors the gateway serves are copied over
    assert 'api_flavor: chat' in output_yaml
    assert 'api_flavor: responses' in output_yaml
    assert 'api_flavor: realtime' not in output_yaml
    output = capsys.readouterr().out
    assert output.count('Created ') == 2
    assert output.count('Collapsed and saved ') == 1
    assert len([provider_yaml for provider_yaml in FakeProviderYaml.instances if provider_yaml.saved]) == 1


def test_quicksilverpro_main_reports_request_errors(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
):
    def fake_get(_: str, *, timeout: float) -> None:
        assert timeout == 30.0
        raise RuntimeError('not available')

    monkeypatch.setattr(httpx2, 'get', fake_get)

    source_quicksilverpro.main()

    assert capsys.readouterr().out == 'Error fetching QuickSilver Pro catalog: not available\n'


def test_quicksilverpro_main_reports_when_no_models_have_prices(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
):
    class FakeResponse:
        def raise_for_status(self) -> None:
            pass

        def json(self) -> dict[str, list[dict[str, object]]]:
            return {
                'models': [
                    {'id': 'free', 'pricing_unit': 'tokens', 'input_per_1m': 0, 'output_per_1m': 0},
                    {'id': 'image-only', 'pricing_unit': 'image', 'output_per_image': 0.03},
                ]
            }

    def fake_get(_: str, *, timeout: float) -> FakeResponse:
        assert timeout == 30.0
        return FakeResponse()

    monkeypatch.setattr(httpx2, 'get', fake_get)

    source_quicksilverpro.main()

    assert capsys.readouterr().out == 'No valid models found with pricing information\n'
