import re
import subprocess
from pathlib import Path

from .utils import package_dir as this_package_dir


def package_data():
    """Prep python package data."""

    from genai_prices.types import __file__ as genai_prices_file, providers_schema

    data_path = this_package_dir / 'data.json'

    providers_schema.rebuild()
    providers = providers_schema.validate_json(data_path.read_bytes())

    data_content = f'''\
"""DO NOT EDIT THIS FILE DIRECTLY, INSTEAD RUN `make package-data`"""
import datetime
from decimal import Decimal

from .types import *

__all__ = ('providers',)

providers: list[Provider] = {providers}
'''

    py_package_dir = Path(genai_prices_file).parent
    data_py = py_package_dir / 'data.py'
    data_py.write_text(data_content)
    root_dir = this_package_dir.parent
    subprocess.run(['uv', 'run', 'ruff', 'format', str(data_py)], cwd=str(root_dir), check=True, stdout=subprocess.PIPE)

    data_content = data_py.read_text()
    data_content = re.sub('^ +[a-z_]+=None,$', '', data_content, flags=re.M)
    data_content = re.sub(r'TzInfo\(UTC\)', 'datetime.timezone.utc', data_content)
    data_py.write_text(data_content)
    subprocess.run(
        [
            'uv',
            'run',
            'ruff',
            'format',
            '--config',
            'format.skip-magic-trailing-comma = true',
            '--config',
            'lint.isort.split-on-trailing-comma = false',
            str(data_py),
        ],
        cwd=str(root_dir),
        check=True,
        stdout=subprocess.PIPE,
    )

    print(f'Data successfully written to {data_py.relative_to(root_dir)}')
