from __future__ import annotations

import dataclasses
import json
import re
import subprocess
from collections.abc import Iterable, Iterator
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast

import ruamel.yaml
from typing_extensions import TypeAlias

from .prices_types import ModelPrice
from .utils import package_dir as this_package_dir, root_dir

if TYPE_CHECKING:
    from genai_prices.units import UnitRegistry


def package_data():
    data_path = this_package_dir / 'data.json'
    package_python_data(data_path)
    package_ts_data(data_path)


def package_python_data(data_path: Path):
    """Prep python package data."""

    from genai_prices.types import __file__ as genai_prices_file, providers_schema

    provider_data, unit_families = _load_package_payload(data_path)
    registry = load_unit_registry(unit_families)
    providers_schema.rebuild()
    providers = providers_schema.validate_python(provider_data)
    validate_provider_model_prices(providers, registry)
    validate_provider_extractor_destinations(providers, registry)

    provider_data_content = f'''\
"""DO NOT EDIT THIS FILE DIRECTLY, INSTEAD RUN `make package-data`"""
import datetime
from decimal import Decimal

from .types import *

__all__ = ('providers',)

providers: list[Provider] = {providers}
'''

    unit_data_content = f'''\
"""DO NOT EDIT THIS FILE DIRECTLY, INSTEAD RUN `make package-data`"""
from typing import Any

__all__ = ('unit_families_data',)

unit_families_data: dict[str, Any] = {unit_families!r}
'''

    py_package_dir = Path(genai_prices_file).parent
    data_py = py_package_dir / 'data.py'
    data_py.write_text(provider_data_content)
    _format_generated_python_data(data_py, post_process_provider_reprs=True)
    print(f'Data successfully written to {data_py.relative_to(root_dir)}')

    data_units_py = py_package_dir / 'data_units.py'
    data_units_py.write_text(unit_data_content)
    _format_generated_python_data(data_units_py)
    print(f'Data successfully written to {data_units_py.relative_to(root_dir)}')


def _load_package_payload(data_path: Path) -> tuple[Any, dict[str, Any]]:
    payload = json.loads(data_path.read_bytes())
    if isinstance(payload, dict) and 'unit_families' in payload and 'providers' in payload:
        return cast(Any, payload['providers']), cast(dict[str, Any], payload['unit_families'])
    if isinstance(payload, list):
        return cast(Any, payload), load_unit_families()

    raise ValueError(f'Expected {data_path} to contain Provider[] or {{unit_families, providers}}')


def _format_generated_python_data(path: Path, *, post_process_provider_reprs: bool = False) -> None:
    subprocess.run(['uv', 'run', 'ruff', 'format', str(path)], cwd=str(root_dir), check=True, stdout=subprocess.PIPE)

    if post_process_provider_reprs:
        data_content = path.read_text()
        data_content = re.sub('^ +[a-z_]+=None,$', '', data_content, flags=re.M)
        data_content = re.sub(r'TzInfo\((?:UTC|0)\)', 'datetime.timezone.utc', data_content)
        path.write_text(data_content)

    subprocess.run(
        [
            'uv',
            'run',
            'ruff',
            'format',
            '--config',
            'format.skip-magic-trailing-comma = true',
            '--config',
            'lint.isort.split-on-trailing-comma = false',
            str(path),
        ],
        cwd=str(root_dir),
        check=True,
        stdout=subprocess.PIPE,
    )


def load_unit_families() -> dict[str, Any]:
    yaml = ruamel.yaml.YAML(typ='safe')
    with (this_package_dir / 'units.yml').open() as f:
        unit_families = cast(dict[str, Any], yaml.load(f))  # pyright: ignore[reportUnknownMemberType]

    return unit_families


def load_unit_registry(unit_families: dict[str, Any] | None = None) -> UnitRegistry:
    from prices.export_validation import validate_unit_families

    return validate_unit_families(load_unit_families() if unit_families is None else unit_families)


def validate_provider_model_prices(providers: Iterable[object], registry: UnitRegistry) -> None:
    from genai_prices.validation import validate_model_price

    for provider in providers:
        provider_id = cast(str, getattr(provider, 'id'))
        for model in cast(Iterable[object], getattr(provider, 'models')):
            model_id = cast(str, getattr(model, 'id'))
            for label, model_price in _iter_model_prices(getattr(model, 'prices')):
                try:
                    validate_model_price(_collect_model_price_keys(model_price), registry)
                except ValueError as exc:
                    raise ValueError(f'Invalid model price for {provider_id}/{model_id}{label}: {exc}') from exc


def validate_provider_extractor_destinations(providers: Iterable[object], registry: UnitRegistry) -> None:
    from genai_prices.validation import validate_extractor_destinations

    reported_usage_keys = registry.reported_usage_keys()
    for provider in providers:
        provider_id = cast(str, getattr(provider, 'id'))
        extractors = getattr(provider, 'extractors', None)
        if extractors is None:
            continue

        for index, extractor in enumerate(cast(Iterable[object], extractors)):
            dest_keys = {
                cast(str, getattr(mapping, 'dest'))
                for mapping in cast(Iterable[object], getattr(extractor, 'mappings'))
            }
            try:
                validate_extractor_destinations(dest_keys, reported_usage_keys)
            except ValueError as exc:
                api_flavor = getattr(extractor, 'api_flavor', index)
                raise ValueError(f'Invalid extractor destination for {provider_id}/{api_flavor}: {exc}') from exc


def _iter_model_prices(prices: object) -> Iterator[tuple[str, object]]:
    if isinstance(prices, list):
        for index, conditional_price in enumerate(cast(list[object], prices)):
            yield f'[{index}]', getattr(conditional_price, 'prices')
    else:
        yield '', prices


def _collect_model_price_keys(model_price: object) -> set[str]:
    if isinstance(model_price, ModelPrice):
        declared_keys = {
            field_name for field_name in model_price.__pydantic_fields__ if getattr(model_price, field_name) is not None
        }
        extra_keys = {field_name for field_name, value in (model_price.model_extra or {}).items() if value is not None}
        return declared_keys | extra_keys

    if dataclasses.is_dataclass(model_price):
        return {field.name for field in dataclasses.fields(model_price) if getattr(model_price, field.name) is not None}

    raise TypeError(f'Unsupported model price type: {type(model_price).__name__}')


def package_ts_data(data_path: Path):
    """Generate TypeScript data file from JSON data."""

    provider_data, unit_families = _load_package_payload(data_path)
    fix_ts_constraints(provider_data)

    ts_content = f"""// DO NOT EDIT THIS FILE DIRECTLY, INSTEAD RUN `make package-data`
import type {{ Provider }} from './types'
export const data: Provider[] = {json.dumps(provider_data, indent=2, ensure_ascii=False)};
"""

    units_ts_content = f"""// DO NOT EDIT THIS FILE DIRECTLY, INSTEAD RUN `make package-data`
import type {{ RawFamiliesDict }} from './types'
export const unitFamiliesData: RawFamiliesDict = {json.dumps(unit_families, indent=2, ensure_ascii=False, sort_keys=True)};
"""

    js_package_dir = root_dir / 'packages' / 'js'
    data_ts = js_package_dir / 'src' / 'data.ts'
    data_ts.write_text(ts_content)
    data_units_ts = js_package_dir / 'src' / 'dataUnits.ts'
    data_units_ts.write_text(units_ts_content)

    subprocess.run(
        ['npx', 'prettier', '--write', 'src/data.ts', 'src/dataUnits.ts'],
        cwd=str(js_package_dir),
        check=True,
        stdout=subprocess.PIPE,
    )
    print(f'Data successfully written to {data_ts.relative_to(root_dir)}')
    print(f'Data successfully written to {data_units_ts.relative_to(root_dir)}')


JsonData: TypeAlias = 'None | int | float | str | list[JsonData] | dict[str, JsonData]'


def fix_ts_constraints(json_data: JsonData) -> None:
    """Fix constraints in ConditionalPrice objects."""
    if isinstance(json_data, list):
        for item in json_data:
            fix_ts_constraints(item)
    elif isinstance(json_data, dict):
        # Fix constraints in ConditionalPrice
        if constraint := json_data.get('constraint'):
            if isinstance(constraint, dict) and 'type' not in constraint:
                if 'start_date' in constraint:
                    constraint['type'] = 'start_date'
                elif 'start_time' in constraint and 'end_time' in constraint:
                    constraint['type'] = 'time_of_date'

        # Recurse into nested objects
        for value in json_data.values():
            fix_ts_constraints(value)
