from operator import attrgetter
from pathlib import Path
from typing import Any, cast

import httpx2
from pydantic import HttpUrl

from prices.collapse import collapse_provider
from prices.prices_types import ClauseAnd, ClauseContains, ClauseEquals, ClauseOr, ModelInfo, ModelPrice, Provider
from prices.source_guard import check_no_sharp_drop, check_non_empty
from prices.update import ProviderYaml, ProviderYamlDict, get_provider_yaml_string


def get_model_infos(models: list[dict[str, Any]], provider: str):
    for model in models:
        model_id_prefix = model['owned_by'] + '/'
        model_id = model['id']
        assert model_id.startswith(model_id_prefix)
        model_name = model_id.removeprefix(model_id_prefix)
        matching_providers = [p for p in model['providers'] if p['provider'] == provider]
        if not matching_providers:
            continue
        [provider_info] = matching_providers
        pricing = provider_info.get('pricing')
        if not pricing:
            continue
        yield ModelInfo(
            id=model_id,
            name=model_name,
            prices=ModelPrice(
                input_mtok=pricing['input'] or None,
                output_mtok=pricing['output'] or None,
            ),
            match=ClauseOr(
                or_=[  # pyright: ignore[reportCallIssue]
                    ClauseEquals(equals=model_id.lower()),
                    ClauseEquals(equals=model_id.lower() + '-fast'),
                ]
            ),
            context_window=provider_info.get('context_length'),
        )


def main():
    response = httpx2.get('https://router.huggingface.co/v1/models', timeout=30.0)
    # Without this an error page becomes a KeyError on ['data'] rather than a legible failure.
    response.raise_for_status()
    models = response.json()['data']

    providers = {p['provider'] for model in models for p in model['providers']}
    providers_dir = Path(__file__).parent / '../../providers'

    openai_extractors = ProviderYaml(providers_dir / 'openai.yml').provider.extractors
    assert openai_extractors
    [chat_extractor] = [e for e in openai_extractors if e.api_flavor == 'chat']

    # Build and validate every provider's output before writing any of it. Two reasons: a shape change
    # upstream yields zero `ModelInfo`s from a large `models` list, so counting the raw response would
    # not notice; and validating inside the write loop would leave earlier providers overwritten when a
    # later one fails its check.
    pending: list[tuple[Path, str, list[ModelInfo]]] = []

    for provider in sorted(providers):
        provider_id = f'huggingface_{provider}'
        model_infos = sorted(get_model_infos(models, provider), key=attrgetter('id'))
        if not model_infos:
            continue

        provider_match = ClauseAnd(
            and_=[  # pyright: ignore[reportCallIssue]
                ClauseContains(contains='huggingface'),
                ClauseContains(contains=provider),
            ],
        )
        provider_info = Provider(
            id=provider_id,
            name=f'HuggingFace ({provider})',
            api_pattern=rf'https://router\.huggingface\.co/{provider}',
            models=model_infos,
            pricing_urls=[
                HttpUrl('https://router.huggingface.co/v1/models'),
                HttpUrl('https://huggingface.co/inference/models'),
            ],
            extractors=[chat_extractor],
            provider_match=provider_match,
        )
        yaml_data = cast(
            ProviderYamlDict, provider_info.model_dump(mode='json', exclude_none=True, by_alias=True, warnings=False)
        )

        yaml_string = (
            '# yaml-language-server: $schema=.schema.json\n'
            '# !!!!!!\n'
            '# This is auto-generated by source_huggingface.py and does not support manual edits yet\n'
            '# !!!!!!\n\n'
        ) + get_provider_yaml_string(yaml_data)

        pending.append((providers_dir / f'{provider_id}.yml', yaml_string, model_infos))

    # These overwrite tracked provider YAML, which the published artifacts are built from, so refuse
    # an upstream response that produced nothing usable or that would delete most of what we record.
    check_non_empty('huggingface', sum(len(model_infos) for _, _, model_infos in pending))
    for path, _, model_infos in pending:
        existing_count = len(ProviderYaml(path).provider.models) if path.exists() else 0
        check_no_sharp_drop('huggingface', path.stem, len(model_infos), existing_count)

    for path, yaml_string, _ in pending:
        path.write_text(yaml_string)
        provider_yaml = ProviderYaml(path)
        if collapse_provider(provider_yaml):
            provider_yaml.save()


def get_huggingface_prices():
    """Download and update HuggingFace provider prices."""
    main()


if __name__ == '__main__':
    main()
