from __future__ import annotations

from decimal import Decimal
from operator import attrgetter
from pathlib import Path
from typing import Any, cast

import httpx2
from pydantic import HttpUrl

from prices.collapse import collapse_provider
from prices.prices_types import ClauseEquals, ModelInfo, ModelPrice, Provider
from prices.update import ProviderYaml, ProviderYamlDict, get_provider_yaml_string

CATALOG_URL = 'https://quicksilverpro.io/pricing.json'

# Catalog rates are already USD per million tokens, so no conversion is needed.
PRICE_KEYS = {
    'input_per_1m': 'input_mtok',
    'cached_input_per_1m': 'cache_read_mtok',
    'cache_write_per_1m': 'cache_write_mtok',
    'output_per_1m': 'output_mtok',
    'output_image_per_1m': 'output_image_mtok',
}


def get_model_infos(models: list[dict[str, Any]]):
    """Extract model information from the QuickSilver Pro catalog (`pricing.json`)."""
    for model in models:
        # Image generation is billed per image, which the registry has no unit for.
        if model.get('pricing_unit') != 'tokens':
            continue

        prices = {
            price_key: Decimal(str(model[catalog_key]))
            for catalog_key, price_key in PRICE_KEYS.items()
            if model.get(catalog_key)
        }
        if not prices:
            continue

        yield ModelInfo(
            id=model['id'],
            name=model.get('name') or model['id'],
            match=ClauseEquals(equals=model['id']),
            context_window=model.get('context_tokens'),
            deprecated=True if model.get('lifecycle') == 'deprecated' else None,
            prices=ModelPrice(**prices),
        )


def main():
    """Download and process QuickSilver Pro pricing data."""
    try:
        response = httpx2.get(CATALOG_URL, timeout=30.0)
        response.raise_for_status()
        models = response.json().get('models', [])
    except Exception as e:
        # Exit non-zero so a scheduled or scripted refresh can't report success on stale data.
        raise SystemExit(f'Error fetching QuickSilver Pro catalog: {e}') from e

    providers_dir = Path(__file__).parent / '../../providers'

    # The gateway is OpenAI-compatible for both the chat completions and responses APIs.
    openai_extractors = ProviderYaml(providers_dir / 'openai.yml').provider.extractors
    assert openai_extractors
    extractors = [e for e in openai_extractors if e.api_flavor in ('chat', 'responses')]

    model_infos = sorted(get_model_infos(models), key=attrgetter('id'))
    if not model_infos:
        raise SystemExit('No valid models found with pricing information')

    provider_id = 'quicksilverpro'
    provider_info = Provider(
        id=provider_id,
        name='QuickSilver Pro',
        description='OpenAI-compatible inference gateway serving frontier and open models via one endpoint.',
        api_pattern=r'https://api\.quicksilverpro\.io',
        models=model_infos,
        pricing_urls=[HttpUrl('https://quicksilverpro.io/#pricing'), HttpUrl(CATALOG_URL)],
        extractors=extractors,
    )

    yaml_data = cast(
        ProviderYamlDict, provider_info.model_dump(mode='json', exclude_none=True, by_alias=True, warnings=False)
    )
    yaml_string = (
        '# yaml-language-server: $schema=.schema.json\n'
        '# !!!!!!\n'
        '# This is auto-generated by source_quicksilverpro.py and does not support manual edits yet\n'
        '# !!!!!!\n\n'
    ) + get_provider_yaml_string(yaml_data)

    path = providers_dir / f'{provider_id}.yml'
    path.write_text(yaml_string)
    print(f'Created {path}')

    provider_yaml = ProviderYaml(path)
    if collapse_provider(provider_yaml):
        provider_yaml.save()
        print(f'Collapsed and saved {path}')


def get_quicksilverpro_prices():  # pragma: no cover - thin CLI alias for main
    """Download and update QuickSilver Pro provider prices."""
    main()


if __name__ == '__main__':
    main()
