from decimal import Decimal
from operator import attrgetter
from pathlib import Path
from typing import Any, cast

import httpx2
from pydantic import HttpUrl

from prices.collapse import collapse_provider
from prices.prices_types import ClauseEquals, ClauseOr, ModelInfo, ModelPrice, Provider
from prices.source_guard import check_no_sharp_drop, check_non_empty
from prices.update import ProviderYaml, ProviderYamlDict, get_provider_yaml_string


def get_model_infos(models: list[dict[str, Any]]):
    """Extract model information from OVHcloud AI Endpoints API response."""
    for model in models:
        model_id = model['id']
        pricing = model.get('pricing')

        if not pricing:
            continue

        # Extract pricing information (convert from per-token to per-million-tokens)
        prompt_price = pricing.get('prompt')
        completion_price = pricing.get('completion')

        # Convert to per-million-token pricing as Decimal
        input_mtok = Decimal(prompt_price) * 1_000_000 if prompt_price and float(prompt_price) > 0 else None
        output_mtok = (
            Decimal(completion_price) * 1_000_000 if completion_price and float(completion_price) > 0 else None
        )

        # Skip if no valid pricing
        if input_mtok is None and output_mtok is None:
            continue

        # Create match clauses, avoiding duplicates
        match_clauses = [ClauseEquals(equals=model_id)]
        if model_id.lower() != model_id:
            match_clauses.append(ClauseEquals(equals=model_id.lower()))

        yield ModelInfo(
            id=model_id,
            name=model_id,
            prices=ModelPrice(
                input_mtok=input_mtok,
                output_mtok=output_mtok,
            ),
            match=ClauseOr(
                or_=match_clauses  # pyright: ignore[reportCallIssue]
            )
            if len(match_clauses) > 1
            else match_clauses[0],
            context_window=model.get('context_length'),
        )


def main():
    """Download and process OVHcloud AI Endpoints pricing data."""
    api_url = 'https://oai.endpoints.kepler.ai.cloud.ovh.net/v1/models'

    # Deliberately not wrapped in try/except: this used to swallow every exception into a silent
    # `return`, so a failed fetch printed a line and exited 0 like a successful no-op.
    response = httpx2.get(api_url, timeout=30.0)
    response.raise_for_status()
    models = response.json().get('data', [])
    check_non_empty('ovhcloud', len(models))

    providers_dir = Path(__file__).parent / '../../providers'

    # Get OpenAI extractor configuration to reuse
    openai_extractors = ProviderYaml(providers_dir / 'openai.yml').provider.extractors
    assert openai_extractors
    [chat_extractor] = [e for e in openai_extractors if e.api_flavor == 'chat']

    # Extract and sort model information
    model_infos = sorted(get_model_infos(models), key=attrgetter('id'))

    if not model_infos:
        print('No valid models found with pricing information')
        return

    provider_id = 'ovhcloud'

    # Create provider configuration
    provider_info = Provider(
        id=provider_id,
        name='OVHcloud AI Endpoints',
        api_pattern=r'https://oai\.endpoints\.kepler\.ai\.cloud\.ovh\.net',
        models=model_infos,
        pricing_urls=[
            HttpUrl('https://oai.endpoints.kepler.ai.cloud.ovh.net/v1/models'),
        ],
        extractors=[chat_extractor],
    )

    # Convert to YAML format
    yaml_data = cast(
        ProviderYamlDict, provider_info.model_dump(mode='json', exclude_none=True, by_alias=True, warnings=False)
    )

    yaml_string = (
        '# yaml-language-server: $schema=.schema.json\n'
        '# !!!!!!\n'
        '# This is auto-generated by source_ovhcloud.py and does not support manual edits yet\n'
        '# !!!!!!\n\n'
    ) + get_provider_yaml_string(yaml_data)

    # Write to file. This overwrites tracked provider YAML, which the published artifacts are built
    # from, so refuse a response that would silently delete most of what we already record.
    path = providers_dir / f'{provider_id}.yml'
    existing_count = len(ProviderYaml(path).provider.models) if path.exists() else 0
    check_no_sharp_drop('ovhcloud', provider_id, len(model_infos), existing_count)
    path.write_text(yaml_string)
    print(f'Created {path}')

    # Collapse provider if possible
    provider_yaml = ProviderYaml(path)
    if collapse_provider(provider_yaml):
        provider_yaml.save()
        print(f'Collapsed and saved {path}')


def get_ovhcloud_prices():
    """Download and update OVHcloud AI Endpoints provider prices."""
    main()


if __name__ == '__main__':
    main()
