name: Beta Release
on:
  workflow_dispatch:

jobs:
  beta-release:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"

      - name: Clean install
        run: |
          rm -rf node_modules packages/js/node_modules
          rm -f package-lock.json
          npm install

      - name: Run tests
        run: npm run ci

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Handle beta release
        run: |
          echo "Running smart beta release workflow..."

          # Check if we're in beta mode
          if [ -f ".changeset/pre.json" ]; then
            echo "Already in beta mode. Checking for changesets..."

            # Check if there are changesets to version
            if [ -n "$(find .changeset -name '*.md' -not -name 'README.md')" ]; then
              echo "Found changesets, creating beta version..."
              npm run beta:version
              git add .
              git commit -m "Create beta version"
              git push origin HEAD:smart-${{ github.run_id }}
            else
              echo "No changesets found. Exiting beta mode..."
              npm run beta:exit
              npm run beta:version
              git add .
              git commit -m "Exit beta mode and create stable version"
              git push origin HEAD:smart-${{ github.run_id }}
            fi
          else
            echo "Not in beta mode. Entering beta mode..."
            npm run beta:enter
            git add .changeset/pre.json
            git commit -m "Enter beta release mode"
            git push origin HEAD:smart-${{ github.run_id }}
          fi
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: smart-${{ github.run_id }}
          base: main
          title: Smart beta release workflow
          body: |
            This PR was automatically created by the beta release workflow.

            **Run ID:** ${{ github.run_id }}

            This smart workflow automatically handles entering beta mode, creating versions, and exiting beta mode based on the current state.
          delete-branch: true
